#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Bloom-Filter
version:      0.01
version_from: Filter.pm
installdirs:  site
requires:
    Carp:                          0.01
    MIME::Base64:                  0.01
    Digest::SHA1:                  0.01

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.12
