---
abstract: 'Sample Perl Bloom filter implementation'
author:
  - 'Maciej Ceglowski <maciej@ceglowski.com>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.9, CPAN::Meta::Converter version 2.133380'
license: open_source
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Bloom-Filter
no_index:
  directory:
    - t
    - inc
requires:
  Carp: 0
  Digest::SHA: 0
  perl: 5.006000
  strict: 0
  warnings: 0
resources:
  bugtracker: https://rt.cpan.org/Dist/Display.html?Name=Bloom-Filter
  repository: git://github.com/Xaerxess/Bloom-Filter.git
version: 1.1
